
[package]
name = "vx_bevy"
version = "0.2.0"
authors = ["Lucas A. <game4allyt@gmail.com>"]
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.0"

[profile.dev]
opt-level = 3

[profile.release]
lto = true