
[package]
name = "vx_bevy"
version = "0.2.0"
authors = ["Lucas A. <game4allyt@gmail.com>"]
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }
ndshape = "0.2.0"
block-mesh = "0.1.0"
ndcopy = "0.2.0"
thread_local = "1.1.4"
bevy_egui = "0.11.1"
futures-lite = "1.12.0"

[profile.dev]
opt-level = 3

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy" }

[profile.release]
lto = true