[package]
name = "vx_bevy"
version = "0.1.0"
authors = ["Lucas A. <game4allyt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vx_core = { path = "crates/vx_core" }
vx_client = { path = "crates/vx_client" }
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
heron = "0.8.0"

[replace]
"bevy:0.5.0" = { git = "https://github.com/bevyengine/bevy", branch = "main" }

[profile.release]
lto = true